name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Uninstall globally installed referrals (if any)
        run: |
          python -m pip uninstall -y referrals || true  # Uninstall if globally installed

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install the package in editable mode

      - name: Set environment variables
        run: echo "BASE_REFERRAL_LINK=http://localhost:8000/" >> $GITHUB_ENV

      - name: Set up the test database
        run: |
          python test_app/manage.py migrate --noinput

      - name: Run Django tests
        run: |
          python test_app/manage.py test referrals